python train.py \
    --dataset_path tokenized_plato_works \
    --num_epochs 16 \
    --batch_size 32 \
    --val_loss_every 8 \
    --learning_rate 0.00005 \
    --weight_decay 0.1 \
    --num_token_permutations 16 \
    --project_name plato-pt \
